//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RietRobHaushaltsbuch.Modules.CarRefuelTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RietRobHaushaltsbuch.Modules.CarRefuelTracker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Entry ähnelt.
        /// </summary>
        public static string btnAddEntry {
            get {
                return ResourceManager.GetString("btnAddEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brand - ähnelt.
        /// </summary>
        public static string btnBrandMinus {
            get {
                return ResourceManager.GetString("btnBrandMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brand + ähnelt.
        /// </summary>
        public static string btnBrandPlus {
            get {
                return ResourceManager.GetString("btnBrandPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string btnCreateCar {
            get {
                return ResourceManager.GetString("btnCreateCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string btnDeleteCar {
            get {
                return ResourceManager.GetString("btnDeleteCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Entry ähnelt.
        /// </summary>
        public static string btnDeleteEntry {
            get {
                return ResourceManager.GetString("btnDeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string btnEditCar {
            get {
                return ResourceManager.GetString("btnEditCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Entry ähnelt.
        /// </summary>
        public static string btnEditEntry {
            get {
                return ResourceManager.GetString("btnEditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fueltype - ähnelt.
        /// </summary>
        public static string btnFuelTypeMinus {
            get {
                return ResourceManager.GetString("btnFuelTypeMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fueltype + ähnelt.
        /// </summary>
        public static string btnFuelTypePlus {
            get {
                return ResourceManager.GetString("btnFuelTypePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model - ähnelt.
        /// </summary>
        public static string btnModelMinus {
            get {
                return ResourceManager.GetString("btnModelMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model + ähnelt.
        /// </summary>
        public static string btnModelPlus {
            get {
                return ResourceManager.GetString("btnModelPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fueltype ähnelt.
        /// </summary>
        public static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Car Refuel Tracker ähnelt.
        /// </summary>
        public static string TitleCarRefuelTrackerOverView {
            get {
                return ResourceManager.GetString("TitleCarRefuelTrackerOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Car Model ähnelt.
        /// </summary>
        public static string txtAddCarModel {
            get {
                return ResourceManager.GetString("txtAddCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Fueltype ähnelt.
        /// </summary>
        public static string txtAddFuelType {
            get {
                return ResourceManager.GetString("txtAddFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount of Fuel ähnelt.
        /// </summary>
        public static string txtAmountOfFuel {
            get {
                return ResourceManager.GetString("txtAmountOfFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Amount Of Fuel: ähnelt.
        /// </summary>
        public static string txtAmountOfFuelTotal {
            get {
                return ResourceManager.GetString("txtAmountOfFuelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Averrage Consumption / 100km ähnelt.
        /// </summary>
        public static string txtAverageConsumptionHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtAverageConsumptionHeaderCarEntryOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ø Fuel Consumption: ähnelt.
        /// </summary>
        public static string txtAverageConsumptionTotal {
            get {
                return ResourceManager.GetString("txtAverageConsumptionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Averrage Cost / 100km ähnelt.
        /// </summary>
        public static string txtAverageCostHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtAverageCostHeaderCarEntryOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ø Costs / 100km: ähnelt.
        /// </summary>
        public static string txtAverageCostsTotal {
            get {
                return ResourceManager.GetString("txtAverageCostsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ø Price/Liter: ähnelt.
        /// </summary>
        public static string txtAveragePriceTotal {
            get {
                return ResourceManager.GetString("txtAveragePriceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brand: ähnelt.
        /// </summary>
        public static string txtBlockBrandLabel {
            get {
                return ResourceManager.GetString("txtBlockBrandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Car Brand ähnelt.
        /// </summary>
        public static string txtBlockHeadline {
            get {
                return ResourceManager.GetString("txtBlockHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Brand  ähnelt.
        /// </summary>
        public static string txtBrand {
            get {
                return ResourceManager.GetString("txtBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle ID: ähnelt.
        /// </summary>
        public static string txtCarId {
            get {
                return ResourceManager.GetString("txtCarId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Costs Total: ähnelt.
        /// </summary>
        public static string txtCostsTotal {
            get {
                return ResourceManager.GetString("txtCostsTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string txtDate {
            get {
                return ResourceManager.GetString("txtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driven Distance ähnelt.
        /// </summary>
        public static string txtDrivenDistance {
            get {
                return ResourceManager.GetString("txtDrivenDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Driven Distance: ähnelt.
        /// </summary>
        public static string txtDrivenDistanceTotal {
            get {
                return ResourceManager.GetString("txtDrivenDistanceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry ID ähnelt.
        /// </summary>
        public static string txtEntryID {
            get {
                return ResourceManager.GetString("txtEntryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Car entrys for the Year: ähnelt.
        /// </summary>
        public static string txtEntrysForYear {
            get {
                return ResourceManager.GetString("txtEntrysForYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is Active ähnelt.
        /// </summary>
        public static string txtIsActive {
            get {
                return ResourceManager.GetString("txtIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model ähnelt.
        /// </summary>
        public static string txtModel {
            get {
                return ResourceManager.GetString("txtModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price per l in € ähnelt.
        /// </summary>
        public static string txtPricePerLiter {
            get {
                return ResourceManager.GetString("txtPricePerLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Costs ähnelt.
        /// </summary>
        public static string txtTotalCosts {
            get {
                return ResourceManager.GetString("txtTotalCosts", resourceCulture);
            }
        }
    }
}
