//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RietRobHaushaltsbuch.Modules.CarRefuelTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RietRobHaushaltsbuch.Modules.CarRefuelTracker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string btnCreateCar {
            get {
                return ResourceManager.GetString("btnCreateCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string btnDeleteCar {
            get {
                return ResourceManager.GetString("btnDeleteCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string btnEditCar {
            get {
                return ResourceManager.GetString("btnEditCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Car Refuel Tracker ähnelt.
        /// </summary>
        public static string TitleCarRefuelTrackerOverView {
            get {
                return ResourceManager.GetString("TitleCarRefuelTrackerOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount of Fuel ähnelt.
        /// </summary>
        public static string txtAmountOfFuelHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtAmountOfFuelHeaderCarEntryOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Averrage Consumption / 100km ähnelt.
        /// </summary>
        public static string txtAverageConsumptionHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtAverageConsumptionHeaderCarEntryOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Averrage Cost / 100km ähnelt.
        /// </summary>
        public static string txtAverageCostHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtAverageCostHeaderCarEntryOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brand: ähnelt.
        /// </summary>
        public static string txtBlockBrandLabel {
            get {
                return ResourceManager.GetString("txtBlockBrandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Car Brand ähnelt.
        /// </summary>
        public static string txtBlockHeadline {
            get {
                return ResourceManager.GetString("txtBlockHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Brand  ähnelt.
        /// </summary>
        public static string txtBrandHeaderFuelTrackerOverView {
            get {
                return ResourceManager.GetString("txtBrandHeaderFuelTrackerOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string txtDateHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtDateHeaderCarEntryOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driven Distance ähnelt.
        /// </summary>
        public static string txtDrivenDistanceHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtDrivenDistanceHeaderCarEntryOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fueltype ähnelt.
        /// </summary>
        public static string txtFuelTypeFuelTrackerOverView {
            get {
                return ResourceManager.GetString("txtFuelTypeFuelTrackerOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die is Active ähnelt.
        /// </summary>
        public static string txtIsActiveFuelTrackerOverView {
            get {
                return ResourceManager.GetString("txtIsActiveFuelTrackerOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model ähnelt.
        /// </summary>
        public static string txtModelHeaderFuelTrackerOverView {
            get {
                return ResourceManager.GetString("txtModelHeaderFuelTrackerOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price per l in € ähnelt.
        /// </summary>
        public static string txtPricePerLiterHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtPricePerLiterHeaderCarEntryOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Costs ähnelt.
        /// </summary>
        public static string txtTotalCostsHeaderCarEntryOverView {
            get {
                return ResourceManager.GetString("txtTotalCostsHeaderCarEntryOverView", resourceCulture);
            }
        }
    }
}
